//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriDataPlane) DeepCopyInto(out *BoriDataPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriDataPlane.
func (in *BoriDataPlane) DeepCopy() *BoriDataPlane {
	if in == nil {
		return nil
	}
	out := new(BoriDataPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoriDataPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriDataPlaneList) DeepCopyInto(out *BoriDataPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoriDataPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriDataPlaneList.
func (in *BoriDataPlaneList) DeepCopy() *BoriDataPlaneList {
	if in == nil {
		return nil
	}
	out := new(BoriDataPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoriDataPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriDataPlaneSpec) DeepCopyInto(out *BoriDataPlaneSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriDataPlaneSpec.
func (in *BoriDataPlaneSpec) DeepCopy() *BoriDataPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(BoriDataPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriDataPlaneStatus) DeepCopyInto(out *BoriDataPlaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ComponentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriDataPlaneStatus.
func (in *BoriDataPlaneStatus) DeepCopy() *BoriDataPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(BoriDataPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriRelease) DeepCopyInto(out *BoriRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriRelease.
func (in *BoriRelease) DeepCopy() *BoriRelease {
	if in == nil {
		return nil
	}
	out := new(BoriRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoriRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriReleaseBaselinePolicy) DeepCopyInto(out *BoriReleaseBaselinePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriReleaseBaselinePolicy.
func (in *BoriReleaseBaselinePolicy) DeepCopy() *BoriReleaseBaselinePolicy {
	if in == nil {
		return nil
	}
	out := new(BoriReleaseBaselinePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriReleaseCompatibilityRef) DeepCopyInto(out *BoriReleaseCompatibilityRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriReleaseCompatibilityRef.
func (in *BoriReleaseCompatibilityRef) DeepCopy() *BoriReleaseCompatibilityRef {
	if in == nil {
		return nil
	}
	out := new(BoriReleaseCompatibilityRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriReleaseComponentRef) DeepCopyInto(out *BoriReleaseComponentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriReleaseComponentRef.
func (in *BoriReleaseComponentRef) DeepCopy() *BoriReleaseComponentRef {
	if in == nil {
		return nil
	}
	out := new(BoriReleaseComponentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriReleaseList) DeepCopyInto(out *BoriReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoriRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriReleaseList.
func (in *BoriReleaseList) DeepCopy() *BoriReleaseList {
	if in == nil {
		return nil
	}
	out := new(BoriReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoriReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriReleasePromotionPolicy) DeepCopyInto(out *BoriReleasePromotionPolicy) {
	*out = *in
	out.BaselinePolicy = in.BaselinePolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriReleasePromotionPolicy.
func (in *BoriReleasePromotionPolicy) DeepCopy() *BoriReleasePromotionPolicy {
	if in == nil {
		return nil
	}
	out := new(BoriReleasePromotionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriReleaseSpec) DeepCopyInto(out *BoriReleaseSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]BoriReleaseComponentRef, len(*in))
		copy(*out, *in)
	}
	out.Compatibility = in.Compatibility
	in.Verification.DeepCopyInto(&out.Verification)
	out.Promotion = in.Promotion
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriReleaseSpec.
func (in *BoriReleaseSpec) DeepCopy() *BoriReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(BoriReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriReleaseStatus) DeepCopyInto(out *BoriReleaseStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriReleaseStatus.
func (in *BoriReleaseStatus) DeepCopy() *BoriReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(BoriReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriReleaseVerification) DeepCopyInto(out *BoriReleaseVerification) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriReleaseVerification.
func (in *BoriReleaseVerification) DeepCopy() *BoriReleaseVerification {
	if in == nil {
		return nil
	}
	out := new(BoriReleaseVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriRevision) DeepCopyInto(out *BoriRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriRevision.
func (in *BoriRevision) DeepCopy() *BoriRevision {
	if in == nil {
		return nil
	}
	out := new(BoriRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoriRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriRevisionList) DeepCopyInto(out *BoriRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoriRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriRevisionList.
func (in *BoriRevisionList) DeepCopy() *BoriRevisionList {
	if in == nil {
		return nil
	}
	out := new(BoriRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoriRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriRevisionSpec) DeepCopyInto(out *BoriRevisionSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]RevisionComponentRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriRevisionSpec.
func (in *BoriRevisionSpec) DeepCopy() *BoriRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(BoriRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoriRevisionStatus) DeepCopyInto(out *BoriRevisionStatus) {
	*out = *in
	if in.PromotedAt != nil {
		in, out := &in.PromotedAt, &out.PromotedAt
		*out = (*in).DeepCopy()
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoriRevisionStatus.
func (in *BoriRevisionStatus) DeepCopy() *BoriRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(BoriRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionComponentRef) DeepCopyInto(out *RevisionComponentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionComponentRef.
func (in *RevisionComponentRef) DeepCopy() *RevisionComponentRef {
	if in == nil {
		return nil
	}
	out := new(RevisionComponentRef)
	in.DeepCopyInto(out)
	return out
}
