apiVersion: apps/v1
kind: Deployment
metadata:
  name: tori
  namespace: tori-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tori
  template:
    metadata:
      labels:
        app: tori
    spec:
      containers:
        - name: tori
          image: ghcr.io/heainseo/tori:v0.1.0
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
