name: multipass

cluster:
  kubeconfig: ${KUBECONFIG}
  context: multipass

namespacePolicy:
  allowed:
    - jumi-system
    - artifact-system
    - nan-system
    - tori-system
  allowClusterScopedResources: false

registry:
  default: ghcr.io/heainseo

secrets:
  mode: reference-only
  redaction: strict
