//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssertionBinding) DeepCopyInto(out *AssertionBinding) {
	*out = *in
	out.Provider = in.Provider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssertionBinding.
func (in *AssertionBinding) DeepCopy() *AssertionBinding {
	if in == nil {
		return nil
	}
	out := new(AssertionBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssertionSlot) DeepCopyInto(out *AssertionSlot) {
	*out = *in
	if in.Enum != nil {
		in, out := &in.Enum, &out.Enum
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.MaxAge = in.MaxAge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssertionSlot.
func (in *AssertionSlot) DeepCopy() *AssertionSlot {
	if in == nil {
		return nil
	}
	out := new(AssertionSlot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Capability) DeepCopyInto(out *Capability) {
	*out = *in
	out.Type = in.Type
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]Requirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Capability.
func (in *Capability) DeepCopy() *Capability {
	if in == nil {
		return nil
	}
	out := new(Capability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityStatus) DeepCopyInto(out *CapabilityStatus) {
	*out = *in
	out.Type = in.Type
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]StatusReason, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityStatus.
func (in *CapabilityStatus) DeepCopy() *CapabilityStatus {
	if in == nil {
		return nil
	}
	out := new(CapabilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityType) DeepCopyInto(out *CapabilityType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityType.
func (in *CapabilityType) DeepCopy() *CapabilityType {
	if in == nil {
		return nil
	}
	out := new(CapabilityType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractPin) DeepCopyInto(out *ContractPin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractPin.
func (in *ContractPin) DeepCopy() *ContractPin {
	if in == nil {
		return nil
	}
	out := new(ContractPin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeniedReference) DeepCopyInto(out *DeniedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeniedReference.
func (in *DeniedReference) DeepCopy() *DeniedReference {
	if in == nil {
		return nil
	}
	out := new(DeniedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyBinding) DeepCopyInto(out *DependencyBinding) {
	*out = *in
	out.Target = in.Target
	out.Contract = in.Contract
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyBinding.
func (in *DependencyBinding) DeepCopy() *DependencyBinding {
	if in == nil {
		return nil
	}
	out := new(DependencyBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRequirement) DeepCopyInto(out *DependencyRequirement) {
	*out = *in
	out.Capability = in.Capability
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRequirement.
func (in *DependencyRequirement) DeepCopy() *DependencyRequirement {
	if in == nil {
		return nil
	}
	out := new(DependencyRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencySlot) DeepCopyInto(out *DependencySlot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencySlot.
func (in *DependencySlot) DeepCopy() *DependencySlot {
	if in == nil {
		return nil
	}
	out := new(DependencySlot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyTargetReference) DeepCopyInto(out *DependencyTargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyTargetReference.
func (in *DependencyTargetReference) DeepCopy() *DependencyTargetReference {
	if in == nil {
		return nil
	}
	out := new(DependencyTargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Envelope) DeepCopyInto(out *Envelope) {
	*out = *in
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make([]Predicate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Envelope.
func (in *Envelope) DeepCopy() *Envelope {
	if in == nil {
		return nil
	}
	out := new(Envelope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvelopeStatus) DeepCopyInto(out *EnvelopeStatus) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]StatusReason, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvelopeStatus.
func (in *EnvelopeStatus) DeepCopy() *EnvelopeStatus {
	if in == nil {
		return nil
	}
	out := new(EnvelopeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceStatus) DeepCopyInto(out *EvidenceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceStatus.
func (in *EvidenceStatus) DeepCopy() *EvidenceStatus {
	if in == nil {
		return nil
	}
	out := new(EvidenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InteractionCandidate) DeepCopyInto(out *InteractionCandidate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InteractionCandidate.
func (in *InteractionCandidate) DeepCopy() *InteractionCandidate {
	if in == nil {
		return nil
	}
	out := new(InteractionCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InteractionCapability) DeepCopyInto(out *InteractionCapability) {
	*out = *in
	out.Type = in.Type
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]StatusReason, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InteractionCapability.
func (in *InteractionCapability) DeepCopy() *InteractionCapability {
	if in == nil {
		return nil
	}
	out := new(InteractionCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InteractionInvestigation) DeepCopyInto(out *InteractionInvestigation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InteractionInvestigation.
func (in *InteractionInvestigation) DeepCopy() *InteractionInvestigation {
	if in == nil {
		return nil
	}
	out := new(InteractionInvestigation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InteractionResponse) DeepCopyInto(out *InteractionResponse) {
	*out = *in
	out.For = in.For
	if in.Risks != nil {
		in, out := &in.Risks, &out.Risks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Preconditions != nil {
		in, out := &in.Preconditions, &out.Preconditions
		*out = make([]StatusReason, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InteractionResponse.
func (in *InteractionResponse) DeepCopy() *InteractionResponse {
	if in == nil {
		return nil
	}
	out := new(InteractionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InteractionStatus) DeepCopyInto(out *InteractionStatus) {
	*out = *in
	if in.LevelReasons != nil {
		in, out := &in.LevelReasons, &out.LevelReasons
		*out = make([]StatusReason, len(*in))
		copy(*out, *in)
	}
	if in.Affected != nil {
		in, out := &in.Affected, &out.Affected
		*out = make([]InteractionCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unaffected != nil {
		in, out := &in.Unaffected, &out.Unaffected
		*out = make([]InteractionCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unknown != nil {
		in, out := &in.Unknown, &out.Unknown
		*out = make([]InteractionCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfirmedFacts != nil {
		in, out := &in.ConfirmedFacts, &out.ConfirmedFacts
		*out = make([]EvidenceStatus, len(*in))
		copy(*out, *in)
	}
	if in.MissingEvidence != nil {
		in, out := &in.MissingEvidence, &out.MissingEvidence
		*out = make([]EvidenceStatus, len(*in))
		copy(*out, *in)
	}
	if in.CauseCandidates != nil {
		in, out := &in.CauseCandidates, &out.CauseCandidates
		*out = make([]InteractionCandidate, len(*in))
		copy(*out, *in)
	}
	if in.Investigation != nil {
		in, out := &in.Investigation, &out.Investigation
		*out = new(InteractionInvestigation)
		**out = **in
	}
	if in.Responses != nil {
		in, out := &in.Responses, &out.Responses
		*out = make([]InteractionResponse, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HumanReasons != nil {
		in, out := &in.HumanReasons, &out.HumanReasons
		*out = make([]StatusReason, len(*in))
		copy(*out, *in)
	}
	if in.PendingPostConditions != nil {
		in, out := &in.PendingPostConditions, &out.PendingPostConditions
		*out = make([]StatusReason, len(*in))
		copy(*out, *in)
	}
	if in.RecentFingerprints != nil {
		in, out := &in.RecentFingerprints, &out.RecentFingerprints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InteractionStatus.
func (in *InteractionStatus) DeepCopy() *InteractionStatus {
	if in == nil {
		return nil
	}
	out := new(InteractionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalContractReference) DeepCopyInto(out *LocalContractReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalContractReference.
func (in *LocalContractReference) DeepCopy() *LocalContractReference {
	if in == nil {
		return nil
	}
	out := new(LocalContractReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedIdentity) DeepCopyInto(out *ObservedIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedIdentity.
func (in *ObservedIdentity) DeepCopy() *ObservedIdentity {
	if in == nil {
		return nil
	}
	out := new(ObservedIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operand) DeepCopyInto(out *Operand) {
	*out = *in
	if in.Boolean != nil {
		in, out := &in.Boolean, &out.Boolean
		*out = new(bool)
		**out = **in
	}
	if in.Integer != nil {
		in, out := &in.Integer, &out.Integer
		*out = new(int64)
		**out = **in
	}
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operand.
func (in *Operand) DeepCopy() *Operand {
	if in == nil {
		return nil
	}
	out := new(Operand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalContract) DeepCopyInto(out *OperationalContract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalContract.
func (in *OperationalContract) DeepCopy() *OperationalContract {
	if in == nil {
		return nil
	}
	out := new(OperationalContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationalContract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalContractList) DeepCopyInto(out *OperationalContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperationalContract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalContractList.
func (in *OperationalContractList) DeepCopy() *OperationalContractList {
	if in == nil {
		return nil
	}
	out := new(OperationalContractList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationalContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalContractSpec) DeepCopyInto(out *OperationalContractSpec) {
	*out = *in
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = make([]AssertionSlot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DependencySlots != nil {
		in, out := &in.DependencySlots, &out.DependencySlots
		*out = make([]DependencySlot, len(*in))
		copy(*out, *in)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]Capability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Envelopes != nil {
		in, out := &in.Envelopes, &out.Envelopes
		*out = make([]Envelope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalContractSpec.
func (in *OperationalContractSpec) DeepCopy() *OperationalContractSpec {
	if in == nil {
		return nil
	}
	out := new(OperationalContractSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalContractStatus) DeepCopyInto(out *OperationalContractStatus) {
	*out = *in
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalContractStatus.
func (in *OperationalContractStatus) DeepCopy() *OperationalContractStatus {
	if in == nil {
		return nil
	}
	out := new(OperationalContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalReferenceGrant) DeepCopyInto(out *OperationalReferenceGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalReferenceGrant.
func (in *OperationalReferenceGrant) DeepCopy() *OperationalReferenceGrant {
	if in == nil {
		return nil
	}
	out := new(OperationalReferenceGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationalReferenceGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalReferenceGrantList) DeepCopyInto(out *OperationalReferenceGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperationalReferenceGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalReferenceGrantList.
func (in *OperationalReferenceGrantList) DeepCopy() *OperationalReferenceGrantList {
	if in == nil {
		return nil
	}
	out := new(OperationalReferenceGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationalReferenceGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalReferenceGrantSpec) DeepCopyInto(out *OperationalReferenceGrantSpec) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = make([]ReferenceGrantFrom, len(*in))
		copy(*out, *in)
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]ReferenceGrantTo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalReferenceGrantSpec.
func (in *OperationalReferenceGrantSpec) DeepCopy() *OperationalReferenceGrantSpec {
	if in == nil {
		return nil
	}
	out := new(OperationalReferenceGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalTarget) DeepCopyInto(out *OperationalTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalTarget.
func (in *OperationalTarget) DeepCopy() *OperationalTarget {
	if in == nil {
		return nil
	}
	out := new(OperationalTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationalTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalTargetList) DeepCopyInto(out *OperationalTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperationalTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalTargetList.
func (in *OperationalTargetList) DeepCopy() *OperationalTargetList {
	if in == nil {
		return nil
	}
	out := new(OperationalTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationalTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalTargetSpec) DeepCopyInto(out *OperationalTargetSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.ContractRef = in.ContractRef
	if in.AssertionBindings != nil {
		in, out := &in.AssertionBindings, &out.AssertionBindings
		*out = make([]AssertionBinding, len(*in))
		copy(*out, *in)
	}
	if in.DependencyBindings != nil {
		in, out := &in.DependencyBindings, &out.DependencyBindings
		*out = make([]DependencyBinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalTargetSpec.
func (in *OperationalTargetSpec) DeepCopy() *OperationalTargetSpec {
	if in == nil {
		return nil
	}
	out := new(OperationalTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationalTargetStatus) DeepCopyInto(out *OperationalTargetStatus) {
	*out = *in
	if in.AssessedAt != nil {
		in, out := &in.AssessedAt, &out.AssessedAt
		*out = (*in).DeepCopy()
	}
	out.Identity = in.Identity
	if in.InvalidReasons != nil {
		in, out := &in.InvalidReasons, &out.InvalidReasons
		*out = make([]StatusReason, len(*in))
		copy(*out, *in)
	}
	if in.DeniedReferences != nil {
		in, out := &in.DeniedReferences, &out.DeniedReferences
		*out = make([]DeniedReference, len(*in))
		copy(*out, *in)
	}
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make([]EvidenceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]CapabilityStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Envelopes != nil {
		in, out := &in.Envelopes, &out.Envelopes
		*out = make([]EnvelopeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Interaction != nil {
		in, out := &in.Interaction, &out.Interaction
		*out = new(InteractionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationalTargetStatus.
func (in *OperationalTargetStatus) DeepCopy() *OperationalTargetStatus {
	if in == nil {
		return nil
	}
	out := new(OperationalTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Predicate) DeepCopyInto(out *Predicate) {
	*out = *in
	if in.Operand != nil {
		in, out := &in.Operand, &out.Operand
		*out = new(Operand)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Predicate.
func (in *Predicate) DeepCopy() *Predicate {
	if in == nil {
		return nil
	}
	out := new(Predicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderReference) DeepCopyInto(out *ProviderReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderReference.
func (in *ProviderReference) DeepCopy() *ProviderReference {
	if in == nil {
		return nil
	}
	out := new(ProviderReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferenceGrantFrom) DeepCopyInto(out *ReferenceGrantFrom) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferenceGrantFrom.
func (in *ReferenceGrantFrom) DeepCopy() *ReferenceGrantFrom {
	if in == nil {
		return nil
	}
	out := new(ReferenceGrantFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferenceGrantTo) DeepCopyInto(out *ReferenceGrantTo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferenceGrantTo.
func (in *ReferenceGrantTo) DeepCopy() *ReferenceGrantTo {
	if in == nil {
		return nil
	}
	out := new(ReferenceGrantTo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Requirement) DeepCopyInto(out *Requirement) {
	*out = *in
	if in.Predicate != nil {
		in, out := &in.Predicate, &out.Predicate
		*out = new(Predicate)
		(*in).DeepCopyInto(*out)
	}
	if in.Dependency != nil {
		in, out := &in.Dependency, &out.Dependency
		*out = new(DependencyRequirement)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Requirement.
func (in *Requirement) DeepCopy() *Requirement {
	if in == nil {
		return nil
	}
	out := new(Requirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusReason) DeepCopyInto(out *StatusReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusReason.
func (in *StatusReason) DeepCopy() *StatusReason {
	if in == nil {
		return nil
	}
	out := new(StatusReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}
